<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productName = $objectManager
    ->create('Magento\Catalog\Model\Product')
    ->load($block->getOrder()->getAllItems()[0]->getProductId())->getName();
$productUrl = $objectManager
    ->create('Magento\Catalog\Model\Product')
    ->load($block->getOrder()->getAllItems()[0]->getProductId())->getProductUrl();
$shareUrlFb = "http://www.facebook.com/sharer/sharer.php?s=100&p[url]=" . $productUrl . "&p[title]=" . $productName;
$shareUrlTwitter = "";
?>

        <?php
        if ($block->getOrder()->getTotalItemCount() == 1) :
            $shareUrlTwitter = "https://twitter.com/home?status=I\'ve just bought "
                . $productName
                . " from wheelsNparts Store. "
                . $productUrl;
        else :
            $shareUrlTwitter = "https://twitter.com/home?status=I\'ve just bought "
                . $productName
                . " and other items from wheelsNparts Store. "
                . $productUrl;
        endif;
        ?>

<div class="primary share">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <div class='container'>

        <h1>Share your Airslamit order</h1>

        <div class="facebook">
            <a onclick="openFbPopUp()"><i class="fa fa-facebook fa-3x" aria-hidden="true"></i>
            </a>
        </div>

        <div class="twitter">
            <a onclick="openTwitterPopUp()"><i class="fa fa-twitter fa-3x" aria-hidden="true"></i></a>
        </div>
    </div>
</div>

<script type="text/javascript">
    function openFbPopUp() {
        window.open(
            '<?php echo $shareUrlFb; ?>',
            'facebook-share-dialog',
            'width=626,height=436');
        return false;
    }

    function openTwitterPopUp() {
        window.open(
            '<?php echo $shareUrlTwitter; ?>',
            'facebook-share-dialog',
            'width=626,height=436');
        return false;
    }
</script>

<style>
    .container h1 {
        color: black;
        text-align: center;
        padding: 5px;
        margin: 0;
        font-size: 15px;
        font-family: 'Roboto', sans-serif;
    }

    .share {
        display: inline-block;
        border: 2px solid #ec3237;
        border-radius: 5px;
        clear: both;
        margin-top: 12px;
    }

    .facebook,
    .twitter {
        display: inline-block;
        margin: 10px;
        transition: 1s;
        border-radius: 5px;
    }

    .fa-facebook,
    .fa-twitter,
    .fa-instagram {
        padding: 10px;
        width: 80px;
        text-align: center;
        color: white;
    }

    .facebook:hover,
    .twitter:hover,
    .instagram:hover {
        transform: scale(1.1, 1.1);
        transform: rotate(360deg);
    }

    /*Colors*/

    .facebook {
        background-color: #3b5998;
    }

    .twitter {
        background-color: #5EA9DD;
    }

    .instagram {
        background: linear-gradient(60deg, #F9C556, #F97621, #EA484C, #D72F78, #A93AB5, #5B62D1);
    }

</style>


